# Supabase 프로젝트 설정

[api]
# API 포트
port = 54321
# 스키마 설정
schemas = ["public", "storage", "graphql_public"]
# 추가 검색 경로
extra_search_path = ["public", "extensions"]
# 최대 행 수
max_rows = 1000

[db]
# 데이터베이스 포트
port = 54322

[studio]
# Studio 포트
port = 54323
# API URL
api_url = "http://localhost:54321"

[inbucket]
# Inbucket 포트 (로컬 이메일 테스트용)
port = 54324
# SMTP 포트
smtp_port = 54325
# POP3 포트
pop3_port = 54326

[storage]
# Storage 포트
port = 54327

[edge_runtime]
# Edge Runtime 포트
port = 54328

[functions.send-notification]
# Edge Function별 환경 변수
# 프로덕션에서는 Supabase 대시보드에서 설정
verify_jwt = false